extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/*.bril' change this

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "lvn", 
    "brili -p {args}",
]